Repository BinaryStudioAcademy/bsa-2020-chatito, pull requests merged in 2020-08, with the labels that each got.

#2 Implement access token on the server
  backend/.env.example
  backend/package.json
  backend/src/common/utils/tokenHelper.ts
  backend/src/config/jwtConfig.ts
  backend/src/env.ts
Labels: feature

#15 Implement react routing
  frontend/.eslintrc
  frontend/package.json
  frontend/src/common/enums/Routes.ts
  frontend/src/common/helpers/storageHelper.ts
  frontend/src/common/models/callback/index.tsx
  frontend/src/components/LoaderWrapper/index.tsx
  frontend/src/containers/App/index.tsx
  frontend/src/containers/Header/index.tsx
  frontend/src/containers/Header/styles.module.sass
  frontend/src/containers/Routing/index.tsx
  frontend/src/index.tsx
  frontend/src/reducers/user.ts
  frontend/src/routines/user.ts
  frontend/src/sagas/user.ts
  frontend/src/styles/index.sass
  frontend/src/styles/index.scss
Labels: feature

#17 Create containers for public and private routes
  frontend/package.json
  frontend/src/containers/PrivateRoute/index.tsx
  frontend/src/containers/PublicRoute/index.tsx
  frontend/src/containers/Routing/index.tsx
Labels: feature

#16 Implement authorization for server endpoints
  backend/package.json
  backend/src/api/middlewares/.gitkeep
  backend/src/api/middlewares/authorizationMiddleware.ts
  backend/src/api/middlewares/jwtMiddleware.ts
  backend/src/config/.gitkeep
  backend/src/config/passportConfig.ts
  backend/src/config/routesWhiteListConfig.ts
  backend/src/data/repositories/.gitkeep
  backend/src/data/repositories/userRepository.ts
  backend/src/server.ts
Labels: feature

#14 Add an ability to create a workspace on the server
  backend/src/api/http/workspace.http
  backend/src/api/routes/index.ts
  backend/src/api/routes/workspaceRoutes.ts
  backend/src/common/@types/express/index.d.ts
  backend/src/common/mappers/workspace.ts
  backend/src/common/models/workspace/ICreateWorkspace.ts
  backend/src/common/models/workspace/IWorkspaceResponse.ts
  backend/src/data/entities/User.ts
  backend/src/data/entities/UserEntity.ts
  backend/src/data/entities/Workspace.ts
  backend/src/data/migrations/1596546836493-add_workspace.ts
  backend/src/data/migrations/1596549284144-CreateUser.ts
  backend/src/data/migrations/1596636744538-create-user-and-relations-between-users-and-workspaces.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/data/repositories/workspaceRepository.ts
  backend/src/services/authService.ts
  backend/src/services/workspaceService.ts
  backend/tsconfig.json
Labels: feature

#25 Fix migrations
  backend/src/data/migrations/1596546836493-add_workspace.ts
  backend/src/data/migrations/1596636744538-create-user-and-relations-between-users-and-workspaces.ts
  backend/src/data/migrations/1596707134771-add-workspace-and-user-entities-with-relations.ts
Labels: fix

#12 Feat/sign
  frontend/package.json
  frontend/src/common/enums/LocalStorageFields.ts
  frontend/src/common/helpers/storageHelper.ts
  frontend/src/common/models/auth/auth.ts
  frontend/src/common/models/formik/ValidationSchemas.ts
  frontend/src/common/models/store.ts
  frontend/src/common/models/user/user.ts
  frontend/src/components/InputField/InputField.tsx
  frontend/src/reducers/user.ts
  frontend/src/routines/user.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/SignIn/index.tsx
  frontend/src/scenes/SignIn/styles.module.sass
  frontend/src/scenes/SignUp/index.tsx
  frontend/src/scenes/SignUp/styles.module.sass
  frontend/src/services/authService.ts
  frontend/src/styles/colors.sass
Labels: feature

#20 Feat/edit profile
  backend/package.json
  backend/src/api/routes/userRoute.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/server.ts
  backend/src/services/userService.ts
  frontend/package.json
  frontend/src/common/enums/ModalTypes.ts
  frontend/src/common/models/modal/IShowModalRoutine.ts
  frontend/src/common/models/store.ts
  frontend/src/common/models/user/user.ts
  frontend/src/components/UserPopUp/index.tsx
  frontend/src/containers/App/index.tsx
  frontend/src/containers/EditProfile/index.tsx
  frontend/src/containers/EditProfile/styles.module.sass
  frontend/src/containers/Header/index.tsx
  frontend/src/reducers/index.ts
  frontend/src/reducers/modal.ts
  frontend/src/reducers/user.ts
  frontend/src/routines/modal.ts
  frontend/src/routines/user.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/reducer.ts
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/sagas.ts
  frontend/src/scenes/Workspace/sagas/sagas.ts
  frontend/src/services/workspaceService.ts
Labels: feature

#42 Implement error handling on the server
  backend/src/api/middlewares/errorHandlerMiddleware.ts
  backend/src/common/enums/ErrorCode.ts
  backend/src/common/models/CustomError.ts
  backend/src/server.ts
Labels: feature

#36 Implement refresh token flow
  backend/package.json
  backend/src/api/routes/authRoutes.ts
  backend/src/common/models/refreshToken/ICreateRefreshToken.ts
  backend/src/common/models/refreshToken/IRefreshToken.ts
  backend/src/common/utils/encryptHelper.ts
  backend/src/config/routesWhiteListConfig.ts
  backend/src/data/entities/.gitkeep
  backend/src/data/entities/RefreshToken.ts
  backend/src/data/migrations/.gitkeep
  backend/src/data/migrations/1596794562190-initEntities.ts
  backend/src/data/repositories/refreshTokenRepository.ts
  backend/src/services/authService.ts
  frontend/src/common/enums/LocalStorageFields.ts
  frontend/src/common/helpers/apiHelper.ts
  frontend/src/common/helpers/storageHelper.ts
  frontend/src/common/models/ITokens.ts
Labels: feature

#45 Feat/error boundary
  frontend/src/common/models/error/IErrorBoundaryFormat.ts
  frontend/src/common/models/store.ts
  frontend/src/components/UserPopUp/index.tsx
  frontend/src/containers/App/index.tsx
  frontend/src/containers/ErrorBoundary/index.tsx
  frontend/src/reducers/errorBoundary.ts
  frontend/src/reducers/index.ts
  frontend/src/routines/error.ts
Labels: feature

#37 Implement Delete account possibility
  backend/src/api/routes/userRoute.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/services/userService.ts
  frontend/src/containers/EditProfile/index.tsx
  frontend/src/containers/EditProfile/styles.module.sass
  frontend/src/reducers/user.ts
  frontend/src/routines/user.ts
  frontend/src/sagas/user.ts
  frontend/src/styles/colors.sass
Labels: feature

#38 Implement create channel popup
  frontend/src/common/enums/ModalTypes.ts
  frontend/src/common/models/callback/index.tsx
  frontend/src/common/models/channel/ICreateChannel.ts
  frontend/src/components/CreateChannelForm/index.tsx
  frontend/src/components/CreateChannelForm/styles.module.sass
  frontend/src/components/ModalWindow/index.tsx
  frontend/src/components/ModalWindow/styles.module.sass
  frontend/src/containers/CreateChannelModal/index.tsx
  frontend/src/reducers/modal.ts
  frontend/src/routines/channel.ts
  frontend/src/sagas/channel.ts
  frontend/src/sagas/index.ts
  frontend/src/services/channelService.ts
Labels: feature

#53 Feat/toastr
  frontend/package.json
  frontend/src/containers/App/index.tsx
  frontend/src/reducers/index.ts
  frontend/src/sagas/channel.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/Workspace/sagas/sagas.ts
  frontend/src/styles/index.sass
Labels: feature

#50 Create 404 page
  backend/src/data/repositories/userRepository.ts
  frontend/src/common/enums/Routes.ts
  frontend/src/containers/Routing/index.tsx
  frontend/src/sagas/user.ts
  frontend/src/scenes/PageNotFound/index.tsx
  frontend/src/scenes/PageNotFound/styles.module.sass
  frontend/src/styles/colors.sass
Labels: feature

#47 Add an ability to load posts and add a post to the chat
  backend/src/api/routes/chatRoutes.ts
  backend/src/api/routes/index.ts
  backend/src/api/routes/postRoutes.ts
  backend/src/common/models/post/ICreatePost.ts
  backend/src/common/models/post/IEditPost.ts
  backend/src/common/models/post/IPost.ts
  backend/src/data/repositories/postRepository.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/services/chatService.ts
  backend/src/services/postService.ts
Labels: feature

#56 Feat/toastr
  frontend/src/common/enums/ErrorCode.ts
  frontend/src/sagas/channel.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/Workspace/sagas/sagas.ts
Labels: enhancement

#59 Rewrite using 'run'
  backend/src/api/routes/userRoute.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/services/userService.ts
Labels: fix

#60 fix sign in flow and loading user data, it doesn't work
  backend/src/api/routes/authRoutes.ts
  backend/src/api/routes/userRoute.ts
  frontend/src/containers/PublicRoute/index.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/reducers/user.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/SignIn/index.tsx
  frontend/src/services/authService.ts
Labels: fix

#66 fix all build warnings
  frontend/src/common/hooks/onInputSubmit.ts
  frontend/src/components/SearchInput/index.tsx
  frontend/src/components/TextEditor/index.tsx
  frontend/src/scenes/Chat/containers/ChatHeader/index.tsx
  frontend/src/scenes/ResetPassword/index.tsx
  frontend/src/scenes/Workspace/containers/AddWorkspace/index.tsx
  frontend/src/scenes/Workspace/containers/Header/index.tsx
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/index.tsx
Labels: fix

#67 fix workspace request
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/index.tsx
Labels: fix

#65 Create main page
  frontend/public/index.html
  frontend/src/common/enums/Routes.ts
  frontend/src/common/hooks/onInputSubmit.ts
  frontend/src/common/models/auth/IResetPasswordCallback.ts
  frontend/src/common/models/callback/IBindingActions.ts
  frontend/src/common/models/callback/IBindingCallback1.ts
  frontend/src/components/CreateChannelForm/index.tsx
  frontend/src/components/InputField/InputField.tsx
  frontend/src/components/InputField/styles.module.sass
  frontend/src/components/ModalWindow/index.tsx
  frontend/src/containers/CreateChannelModal/index.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/img/chatitoMascot.svg
  frontend/src/img/logo.svg
  frontend/src/img/signInFacebook.svg
  frontend/src/img/signInGoogle.svg
  frontend/src/sagas/user.ts
  frontend/src/scenes/Auth/components/ForgotPassword/index.tsx
  frontend/src/scenes/Auth/components/ForgotPassword/styles.module.sass
  frontend/src/scenes/Auth/components/ResetPassword/index.tsx
  frontend/src/scenes/Auth/components/ResetPassword/styles.module.sass
  frontend/src/scenes/Auth/components/SignIn/index.tsx
  frontend/src/scenes/Auth/components/SignIn/styles.module.sass
  frontend/src/scenes/Auth/components/SignUp/index.tsx
  frontend/src/scenes/Auth/components/SignUp/styles.module.sass
  frontend/src/scenes/Auth/containers/Auth/index.tsx
  frontend/src/scenes/Auth/containers/Auth/styles.module.sass
  frontend/src/scenes/ForgotPassword/styles.module.sass
  frontend/src/scenes/ResetPassword/styles.module.sass
  frontend/src/scenes/SignIn/index.tsx
  frontend/src/scenes/SignIn/styles.module.sass
  frontend/src/scenes/SignUp/styles.module.sass
  frontend/src/styles/colors.sass
  frontend/src/styles/fonts.sass
  frontend/src/styles/index.sass
Labels: feature

#68 Create main page
  frontend/src/common/enums/Routes.ts
  frontend/src/containers/Routing/index.tsx
  frontend/src/scenes/PageNotFound/index.tsx
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/index.tsx
Labels: fix

#71 fix refreshToken write
  frontend/src/common/models/auth/IAuthServerResponse.ts
  frontend/src/sagas/user.ts
Labels: bug

#70 The token for the forgot password functionality is in invalid place
  backend/src/api/middlewares/authorizationMiddleware.ts
  backend/src/api/middlewares/jwtMiddleware.ts
  backend/src/api/routes/authRoutes.ts
  backend/src/common/models/user/IResetPasswordUser.ts
  backend/src/config/passportConfig.ts
  backend/src/config/routesWhiteListConfig.ts
  backend/src/services/authService.ts
  frontend/src/sagas/user.ts
Labels: bug

#64 Feat/logout
  backend/src/api/routes/authRoutes.ts
  backend/src/services/authService.ts
  frontend/src/components/Logout/index.tsx
  frontend/src/scenes/Workspace/containers/Header/index.tsx
  frontend/src/services/authService.ts
Labels: feature

#54 Implement Profile overview in the SideMenu
  frontend/src/components/ProfileOverview/index.tsx
  frontend/src/components/ProfileOverview/styles.module.sass
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/scenes/Workspace/containers/Workspace/index.tsx
  frontend/src/styles/colors.sass
  frontend/src/styles/index.sass
Labels: feature

#55 Implement Post UI
  frontend/src/common/helpers/dateHelper.ts
  frontend/src/common/models/post/IPost.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/Post/styles.module.sass
Labels: feature

#69 User status + fix sagas logic
  backend/src/api/routes/userRoute.ts
  backend/src/common/mappers/user.ts
  backend/src/common/models/user/IEditStatus.ts
  backend/src/common/models/user/IUser.ts
  backend/src/common/models/user/IUserClient.ts
  backend/src/common/models/user/IUserWithWorkspaces.ts
  backend/src/data/entities/User.ts
  backend/src/data/migrations/1597079612194-addStatusColumnToUser.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/services/userService.ts
  frontend/package.json
  frontend/src/common/models/status/IEditStatusData.ts
  frontend/src/common/models/user/IUser.ts
  frontend/src/components/CreateChannelForm/index.tsx
  frontend/src/components/EmojiPopUp/index.tsx
  frontend/src/components/EmojiPopUp/styles.module.sass
  frontend/src/components/ModalWindow/index.tsx
  frontend/src/components/ProfilePreview/index.tsx
  frontend/src/components/ProfilePreview/styles.module.sass
  frontend/src/components/TextEditor/index.tsx
  frontend/src/components/UserPopUp/index.tsx
  frontend/src/containers/App/index.tsx
  frontend/src/containers/ChangeStatus/index.tsx
  frontend/src/containers/ChangeStatus/styles.module.sass
  frontend/src/containers/Routing/index.tsx
  frontend/src/containers/Thread/index.tsx
  frontend/src/containers/Thread/styles.module.sass
  frontend/src/containers/ThreadsContainer/index.tsx
  frontend/src/containers/ThreadsContainer/reducers/reducer.ts
  frontend/src/containers/ThreadsContainer/routines/index.ts
  frontend/src/containers/ThreadsContainer/sagas/sagas.ts
  frontend/src/containers/ThreadsContainer/styles.module.sass
  frontend/src/reducers/user.ts
  frontend/src/routines/user.ts
  frontend/src/sagas/channel.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/Workspace/components/Thread/index.tsx
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/sagas.ts
  frontend/src/scenes/Workspace/sagas/sagas.ts
  frontend/src/services/threadsService.ts
  frontend/src/services/toastrService.ts
  frontend/src/services/userService.ts
  frontend/src/styles/colors.sass
  frontend/src/styles/index.sass
  frontend/src/styles/reset.sass
Labels: bug, feature

#73 fixing bugs with threadsContainer and userService
  frontend/src/common/models/thread/IThread.ts
  frontend/src/containers/ChangeStatus/index.tsx
  frontend/src/containers/ThreadsContainer/index.tsx
  frontend/src/sagas/user.ts
  frontend/src/services/userService.ts
Labels: bug

#75 Fix warnings
  frontend/src/sagas/user.ts
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/services/userService.ts
Labels: fix

#77 fix/IUser_interface
  frontend/src/common/models/user/IUser.ts
Labels: bug

#76 Feat/left side workspaces
  backend/src/data/repositories/userRepository.ts
  backend/src/services/userService.ts
  frontend/src/common/enums/Routes.ts
  frontend/src/common/models/auth/IAuthServerResponse.ts
  frontend/src/common/models/error/IErrorBoundaryFormat.ts
  frontend/src/common/models/store.ts
  frontend/src/containers/Routing/index.tsx
  frontend/src/reducers/index.ts
  frontend/src/reducers/user.ts
  frontend/src/routines/user.ts
  frontend/src/sagas/index.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/Workspace/containers/AddWorkspace/index.tsx
  frontend/src/scenes/Workspace/containers/ChatToolbar/index.tsx
  frontend/src/scenes/Workspace/containers/ChatToolbar/styles.module.sass
  frontend/src/scenes/Workspace/containers/Workspace/styles.module.sass
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/components/WorkspaceItem/index.tsx
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/components/WorkspaceItem/styles.module.sass
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/index.tsx
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/sagas.ts
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/styles.module.sass
  frontend/src/scenes/Workspace/reducers/index.ts
  frontend/src/scenes/Workspace/routines/index.ts
  frontend/src/scenes/Workspace/sagas/index.ts
  frontend/src/services/workspaceService.ts
  frontend/src/styles/colors.sass
Labels: feature

#41 Create profile preview
  frontend/src/common/hooks/onInputSubmit.ts
  frontend/src/common/models/post/IPost.ts
  frontend/src/common/models/user/IUser.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/ProfilePreview/index.tsx
  frontend/src/components/ProfilePreview/styles.module.sass
  frontend/src/containers/ChangeStatus/styles.module.sass
  frontend/src/containers/Routing/index.tsx
  frontend/src/containers/ThreadsContainer/index.tsx
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/scenes/Workspace/containers/AddWorkspace/styles.module.sass
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/styles.module.sass
  frontend/src/styles/colors.sass
Labels: feature

#83 fix onKey hook
  frontend/src/common/hooks/onInputSubmit.ts
  frontend/src/components/ProfilePreview/index.tsx
Labels: fix

#89 Delete unused context
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
Labels: fix

#87 data-seed
  backend/src/common/utils/arrayHelper.ts
  backend/src/data/seed-data/chats.seed.ts
  backend/src/data/seed-data/comment.seed.ts
  backend/src/data/seed-data/posts.seed.ts
  backend/src/data/seed-data/users.seed.ts
  backend/src/data/seed-data/workspaces.seed.ts
  backend/src/data/seeders/chatSeeder.ts
  backend/src/data/seeders/commentSeeder.ts
  backend/src/data/seeders/index.ts
  backend/src/data/seeders/postSeeder.ts
  backend/src/data/seeders/userSeeder.ts
  backend/src/data/seeders/workspaceSeeder.ts
Labels: feature

#88 Implement Thread overview in the SideMenu [full flow]
  backend/src/api/routes/postRoutes.ts
  backend/src/common/mappers/comment.ts
  backend/src/common/models/comment/ICreateComment.ts
  backend/src/data/repositories/commentRepository.ts
  backend/src/services/postService.ts
  frontend/package.json
  frontend/src/common/enums/RightMenuTypes.ts
  frontend/src/common/models/post/ICreateComment.ts
  frontend/src/common/models/post/IPost.ts
  frontend/src/common/models/thread/IActiveThread.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/Post/styles.module.sass
  frontend/src/components/ProfilePreview/index.tsx
  frontend/src/containers/CreateDirectForm/reducers/reducer.ts
  frontend/src/containers/Thread/index.tsx
  frontend/src/containers/Thread/routines.ts
  frontend/src/containers/Thread/sagas.ts
  frontend/src/containers/Thread/styles.module.sass
  frontend/src/containers/ThreadsContainer/index.tsx
  frontend/src/sagas/index.ts
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/scenes/Workspace/containers/ChatToolbar/components/ParticipantsList/index.tsx
  frontend/src/scenes/Workspace/containers/ChatToolbar/components/ParticipantsList/styles.module.sass
  frontend/src/scenes/Workspace/containers/ChatToolbar/components/Thread/index.tsx
  frontend/src/scenes/Workspace/containers/ChatToolbar/components/Thread/styles.module.sass
  frontend/src/scenes/Workspace/containers/Thread/index.tsx
  frontend/src/scenes/Workspace/containers/Workspace/index.tsx
  frontend/src/scenes/Workspace/containers/Workspace/styles.module.sass
  frontend/src/scenes/Workspace/reducers/index.ts
  frontend/src/scenes/Workspace/routines/index.ts
  frontend/src/scenes/Workspace/sagas/index.ts
  frontend/src/services/threadsService.ts
Labels: feature

#91 Fix/forgotpassword functionality
  backend/src/services/authService.ts
  backend/src/services/mailService.ts
  frontend/src/sagas/user.ts
  frontend/src/services/toastrService.ts
  frontend/src/services/userService.ts
Labels: fix

#90 fix/edit-profile
  frontend/src/containers/EditProfile/index.tsx
  frontend/src/scenes/Workspace/containers/Header/index.tsx
  frontend/src/services/userService.ts
Labels: fix

#86 Combine chats with chat toolbar
  backend/src/common/mappers/post.ts
  backend/src/common/mappers/user.ts
  backend/src/common/models/chat/IChat.ts
  backend/src/common/models/post/ICreatePost.ts
  backend/src/common/models/post/IPost.ts
  backend/src/common/models/post/IPostClient.ts
  backend/src/data/repositories/chatRepository.ts
  backend/src/data/repositories/postRepository.ts
  backend/src/services/chatService.ts
  backend/src/services/postService.ts
  frontend/src/common/models/post/IPost.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/ProfilePreview/index.tsx
  frontend/src/components/TextEditor/index.tsx
  frontend/src/containers/CreateChannelModal/index.tsx
  frontend/src/containers/CreateDirectModal/index.tsx
  frontend/src/containers/Thread/index.tsx
  frontend/src/sagas/index.ts
  frontend/src/scenes/Chat/containers/Chat/index.tsx
  frontend/src/scenes/Chat/containers/Chat/styles.module.sass
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/scenes/Chat/containers/ChatBody/styles.module.sass
  frontend/src/scenes/Chat/containers/ChatFooter/index.tsx
  frontend/src/scenes/Chat/containers/ChatHeader/index.tsx
  frontend/src/scenes/Chat/containers/ChatHeader/styles.module.sass
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/scenes/Workspace/containers/ChatToolbar/index.tsx
  frontend/src/scenes/Workspace/containers/ChatToolbar/styles.module.sass
  frontend/src/scenes/Workspace/containers/Workspace/styles.module.sass
  frontend/src/services/chatServise.ts
Labels: fix

#95 fix/fetching-login-user
  frontend/src/reducers/user.ts
Labels: fix

#97 fix main-UI
  frontend/src/common/helpers/imageHelper.ts
  frontend/src/components/Logout/index.tsx
  frontend/src/components/UserPopUp/index.tsx
  frontend/src/components/UserPopUp/styles.module.sass
  frontend/src/containers/EditProfile/index.tsx
  frontend/src/scenes/Workspace/containers/ChatToolbar/index.tsx
  frontend/src/scenes/Workspace/containers/ChatToolbar/styles.module.sass
  frontend/src/scenes/Workspace/containers/Header/index.tsx
  frontend/src/scenes/Workspace/containers/Header/styles.module.sass
Labels: enhancement

#109 Feat/chat redesign
  frontend/src/components/Post/index.tsx
  frontend/src/components/Post/styles.module.sass
  frontend/src/components/ProfilePreview/index.tsx
  frontend/src/scenes/Chat/containers/Chat/index.tsx
  frontend/src/scenes/Chat/containers/Chat/styles.module.sass
  frontend/src/scenes/Chat/containers/ChatBody/styles.module.sass
  frontend/src/scenes/Chat/containers/NoChatReminder/index.tsx
  frontend/src/scenes/Chat/containers/NoChatReminder/styles.module.sass
  frontend/src/scenes/Workspace/containers/Workspace/styles.module.sass
Labels: feature

#113 fix redirect after adding workspace
  frontend/src/scenes/Workspace/sagas/index.ts
Labels: fix

#116 Fix/invite workspace redirect
  frontend/src/common/enums/Routes.ts
  frontend/src/common/models/store.ts
  frontend/src/containers/JoinInvitedWorkspace/index.tsx
  frontend/src/containers/JoinInvitedWorkspace/reducer.ts
  frontend/src/containers/JoinInvitedWorkspace/sagas.ts
  frontend/src/containers/Routing/index.tsx
  frontend/src/reducers/index.ts
  frontend/src/scenes/Workspace/containers/Workspace/index.tsx
Labels: fix

#118 Update IPost
  backend/src/common/mappers/comment.ts
  backend/src/common/mappers/post.ts
  backend/src/common/models/post/ICommentsInfo.ts
  backend/src/common/models/post/IPostClient.ts
  frontend/src/common/models/post/ICommentsInfo.ts
  frontend/src/common/models/post/IPost.ts
  frontend/src/containers/ThreadsContainer/index.tsx
Labels: feature

#104 Add an ability to react on a post [full flow]
  backend/src/api/http/post.http
  backend/src/api/http/postReaction.http
  backend/src/api/routes/index.ts
  backend/src/api/routes/postReactionRoutes.ts
  backend/src/api/routes/workspaceRoutes.ts
  backend/src/common/mappers/post.ts
  backend/src/common/models/post/IPost.ts
  backend/src/common/models/post/IPostClient.ts
  backend/src/common/models/postReaction/ICreatePostReaction.ts
  backend/src/common/models/postReaction/IDeletePostReaction.ts
  backend/src/common/models/postReaction/IPostReaction.ts
  backend/src/common/models/postReaction/IPostReactionClient.ts
  backend/src/data/entities/Post.ts
  backend/src/data/entities/PostReaction.ts
  backend/src/data/entities/User.ts
  backend/src/data/migrations/1597428417522-addPostReaction.ts
  backend/src/data/repositories/postReactionRepository.ts
  backend/src/data/repositories/postRepository.ts
  backend/src/services/postService.ts
  frontend/src/common/enums/PostType.ts
  frontend/src/common/models/post/IPost.ts
  frontend/src/common/models/postReaction/IPostReaction.ts
  frontend/src/common/models/postReaction/IPostReactionRoutine.ts
  frontend/src/common/models/postReaction/IPostReactionService.ts
  frontend/src/common/models/threads/IFetchedThreads.ts
  frontend/src/components/Post/index.tsx
  frontend/src/components/Post/styles.module.sass
  frontend/src/containers/Post/index.tsx
  frontend/src/containers/Post/routines.ts
  frontend/src/containers/Post/sagas.ts
  frontend/src/containers/Post/styles.module.sass
  frontend/src/containers/Thread/index.tsx
  frontend/src/containers/Thread/styles.module.sass
  frontend/src/containers/ThreadsContainer/index.tsx
  frontend/src/sagas/index.ts
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/services/postService.ts
  frontend/src/styles/colors.sass
  frontend/src/styles/reset.sass
Labels: feature

#114 Implement Sign In using Facebook account
  backend/.env.example
  backend/package.json
  backend/src/api/middlewares/facebookAuthMiddleware.ts
  backend/src/api/routes/authRoutes.ts
  backend/src/common/@types/express/index.d.ts
  backend/src/common/mappers/user.ts
  backend/src/common/models/user/IFacebookUser.ts
  backend/src/common/models/user/ILoginWithFacebook.ts
  backend/src/config/facebookAuthConfig.ts
  backend/src/config/passportConfig.ts
  backend/src/config/routesWhiteListConfig.ts
  backend/src/env.ts
  backend/src/services/authService.ts
  frontend/.env.example
  frontend/package.json
  frontend/src/common/models/auth/ILoginWithFacebook.ts
  frontend/src/config/facebookLoginConfig.ts
  frontend/src/env.ts
  frontend/src/reducers/user.ts
  frontend/src/routines/user.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/Auth/components/SignIn/index.tsx
  frontend/src/scenes/Auth/containers/Auth/index.tsx
  frontend/src/services/authService.ts
Labels: feature

#122 Add infinite loader for chats in Chat
  backend/src/api/routes/chatRoutes.ts
  backend/src/common/models/chat/IGetChatPosts.ts
  backend/src/data/repositories/postRepository.ts
  backend/src/services/chatService.ts
  frontend/package.json
  frontend/src/common/models/post/IFetchMorePosts.ts
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/services/chatService.ts
Labels: feature

#124 Fix/authorized invite
  backend/src/api/routes/userRoute.ts
  backend/src/services/authService.ts
  backend/src/services/userService.ts
  frontend/src/common/models/inviteLink/IAddInviteWorkspace.ts
  frontend/src/containers/JoinInvitedWorkspace/index.tsx
  frontend/src/containers/JoinInvitedWorkspace/routines.ts
  frontend/src/containers/JoinInvitedWorkspace/sagas.ts
  frontend/src/containers/Routing/index.tsx
  frontend/src/reducers/user.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/Workspace/containers/ChatToolbar/index.tsx
  frontend/src/services/inviteLinkService.ts
Labels: enhancement, fix

#125 fix/clear-localstorage
  frontend/src/common/helpers/storageHelper.ts
  frontend/src/sagas/user.ts
Labels: fix

#126 Fix/signup routing
  frontend/src/containers/PublicRoute/index.tsx
  frontend/src/scenes/SignIn/index.tsx
Labels: fix

#127 fix empty messages send
  frontend/src/components/TextEditor/index.tsx
Labels: fix

#128 Fix/invite workspace
  backend/src/services/inviteLinkService.ts
  frontend/src/common/models/fetch/IFetchUser.ts
  frontend/src/containers/InvitePopup/sagas.ts
  frontend/src/containers/Routing/index.tsx
  frontend/src/sagas/user.ts
Labels: fix

#130 mail service changed
  backend/.env.example
  backend/package.json
  backend/src/config/nodeMailer.ts
  backend/src/config/sendgridConfig.ts
  backend/src/env.ts
  backend/src/server.ts
  backend/src/services/mailService.ts
Labels: fix

#134 Fix/publish reply
  backend/src/common/enums/ClientSockets.ts
  backend/src/data/repositories/commentRepository.ts
  backend/src/data/repositories/postRepository.ts
  backend/src/services/postService.ts
  frontend/src/common/enums/ClientSockets.ts
  frontend/src/common/models/post/IServerComment.ts
  frontend/src/containers/ThreadsContainer/index.tsx
  frontend/src/containers/ThreadsContainer/reducers/reducer.ts
  frontend/src/containers/ThreadsContainer/routines/index.ts
  frontend/src/scenes/Workspace/reducers/index.ts
  frontend/src/scenes/Workspace/routines/index.ts
  frontend/src/services/socketService.ts
Labels: fix

#129 Add an ability to add a user to a chat (channel)
  backend/src/api/routes/chatRoutes.ts
  backend/src/data/repositories/chatRepository.ts
  backend/src/data/repositories/workspaceRepository.ts
  backend/src/services/chatService.ts
  backend/src/services/workspaceService.ts
  frontend/src/common/enums/ModalTypes.ts
  frontend/src/common/helpers/searchHelper.ts
  frontend/src/common/models/chat/IAddUsersToChat.ts
  frontend/src/containers/CreateDirectForm/index.tsx
  frontend/src/containers/CreateDirectForm/reducers/reducer.ts
  frontend/src/containers/CreateDirectForm/routines/index.ts
  frontend/src/containers/CreateDirectForm/sagas/sagas.ts
  frontend/src/reducers/modal.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/Chat/containers/ChatHeader/index.tsx
  frontend/src/scenes/Chat/containers/InviteChatModal/index.tsx
  frontend/src/scenes/Chat/containers/InviteChatModal/styles.module.sass
  frontend/src/scenes/Chat/routines/index.ts
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/scenes/Workspace/reducers/index.ts
  frontend/src/scenes/Workspace/routines/index.ts
  frontend/src/scenes/Workspace/sagas/index.ts
  frontend/src/services/chatService.ts
  frontend/src/styles/colors.sass
Labels: feature

#135 Profile overview, preview bugs
  frontend/src/components/ProfileOverview/index.tsx
  frontend/src/components/ProfilePreview/index.tsx
  frontend/src/containers/Post/index.tsx
  frontend/src/containers/Post/styles.module.sass
  frontend/src/containers/Thread/index.tsx
  frontend/src/containers/ThreadsContainer/index.tsx
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/scenes/Workspace/containers/Thread/index.tsx
  frontend/src/scenes/Workspace/containers/Workspace/index.tsx
  frontend/src/scenes/Workspace/reducers/index.ts
Labels: fix

#139 UI bugs in Implement Thread overview in the SideMenu [full flow]
  backend/src/common/mappers/post.ts
  backend/src/common/models/post/IPost.ts
  backend/src/common/models/post/IPostClient.ts
  backend/src/data/repositories/postRepository.ts
  frontend/src/common/models/post/IPost.ts
  frontend/src/containers/Post/index.tsx
  frontend/src/containers/Post/styles.module.sass
  frontend/src/containers/Thread/index.tsx
  frontend/src/containers/Thread/styles.module.sass
  frontend/src/containers/ThreadsContainer/index.tsx
  frontend/src/containers/ThreadsContainer/styles.module.sass
Labels: fix

#145 It's possible to create chat with the same name in one workspace
  frontend/src/containers/CreateChannelModal/index.tsx
Labels: fix

#144 new chat doesn't appear if it is created by new user
  frontend/src/services/socketService.ts
Labels: fix

#141 Inviting user to chat always throws error
  backend/src/services/chatService.ts
Labels: fix

#146 Fix/switch channels
  .gitignore
  backend/src/api/routes/workspaceRoutes.ts
  backend/src/common/mappers/chat.ts
  backend/src/data/repositories/chatRepository.ts
  backend/src/services/workspaceService.ts
  frontend/src/common/models/chat/IChat.ts
  frontend/src/common/models/chat/IFetchWorkspaceChat.ts
  frontend/src/scenes/Workspace/containers/ChatToolbar/index.tsx
  frontend/src/scenes/Workspace/containers/Workspace/index.tsx
  frontend/src/scenes/Workspace/reducers/index.ts
  frontend/src/scenes/Workspace/routines/index.ts
  frontend/src/scenes/Workspace/sagas/index.ts
  frontend/src/services/chatService.ts
  frontend/src/services/socketService.ts
Labels: enhancement, fix

#157 typos
  frontend/src/components/UserPopUp/index.tsx
  frontend/src/scenes/Workspace/containers/ChatToolbar/index.tsx
Labels: fix

#168 Add button disabling
  frontend/src/scenes/Chat/containers/InviteChatModal/index.tsx
Labels: fix

#169 User shouldn't see chats which he didn't join
  backend/src/data/repositories/chatRepository.ts
Labels: fix

#165 Creating many dialogues with same users
  frontend/src/common/models/chat/IChatWithUnread.ts
  frontend/src/containers/CreateDirectForm/index.tsx
  frontend/src/containers/CreateDirectModal/index.tsx
Labels: fix

#173 No header on Not found page
  frontend/src/containers/Header/index.tsx
  frontend/src/containers/Header/styles.module.sass
  frontend/src/scenes/PageNotFound/index.tsx
  frontend/src/scenes/PageNotFound/styles.module.sass
  frontend/src/scenes/Workspace/containers/Workspace/index.tsx
Labels: fix

#170 Edit user profile - page reloading
  frontend/src/containers/EditProfileForm/index.tsx
Labels: fix

#175 Chat members modal doesn't work properly
  backend/src/data/repositories/chatRepository.ts
  frontend/src/containers/ChatMembers/index.tsx
Labels: fix

#177 Implement sockets for post reactions
  backend/src/common/enums/ClientSockets.ts
  backend/src/data/repositories/postReactionRepository.ts
  backend/src/data/repositories/postRepository.ts
  backend/src/services/postService.ts
  frontend/src/common/enums/ClientSockets.ts
  frontend/src/common/models/postReaction/IPostReactionSocket.ts
  frontend/src/containers/Post/routines.ts
  frontend/src/containers/Post/sagas.ts
  frontend/src/reducers/user.ts
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/services/socketService.ts
Labels: feature

#160 Connect functionality to Profile preview and overview
  backend/src/data/repositories/chatRepository.ts
  frontend/src/common/helpers/dateHelper.ts
  frontend/src/common/helpers/nameHelper.ts
  frontend/src/common/models/chat/ICreateChatAndAddPost.ts
  frontend/src/components/ProfileOverview/index.tsx
  frontend/src/containers/Post/index.tsx
  frontend/src/containers/ProfileOverview/index.tsx
  frontend/src/containers/ProfileOverview/styles.module.sass
  frontend/src/containers/ProfilePreview/index.tsx
  frontend/src/containers/ProfilePreview/styles.module.sass
  frontend/src/scenes/Chat/containers/ChatHeader/index.tsx
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/scenes/Chat/routines/index.ts
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/scenes/Workspace/containers/ChatToolbar/index.tsx
  frontend/src/scenes/Workspace/containers/Workspace/index.tsx
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/index.tsx
Labels: feature

#172 In Threads all replies are displayed only for the first message in the channel
  frontend/src/containers/Thread/index.tsx
  frontend/src/scenes/Workspace/reducers/index.ts
Labels: fix

#153 Add reminders functionality and create a reminder popup
  backend/src/api/routes/chatRoutes.ts
  backend/src/common/models/reminder/ICreateReminder.ts
  backend/src/common/models/reminder/ICreateReminderData.ts
  backend/src/common/models/reminder/IReminder.ts
  backend/src/common/models/reminder/IReminderData.ts
  backend/src/data/entities/Chat.ts
  backend/src/data/entities/Reminder.ts
  backend/src/data/entities/User.ts
  backend/src/data/migrations/1597873493673-addReminder.ts
  backend/src/data/repositories/reminderRepository.ts
  backend/src/services/reminderService.ts
  frontend/src/common/enums/ModalTypes.ts
  frontend/src/common/models/reminder/ICreateReminder.ts
  frontend/src/common/models/reminder/IReminder.ts
  frontend/src/components/ReminderItem/ReminderItem.tsx
  frontend/src/components/ReminderItem/styles.module.sass
  frontend/src/containers/CustomReminderModal/index.tsx
  frontend/src/containers/CustomReminderModal/styles.module.sass
  frontend/src/containers/Post/index.tsx
  frontend/src/containers/Post/styles.module.sass
  frontend/src/reducers/modal.ts
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/scenes/Chat/routines/index.ts
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/services/reminderService.ts
Labels: feature

#154 Add Draft messages page
  backend/src/api/http/draft.http
  backend/src/api/routes/index.ts
  backend/src/api/routes/workspaceRoutes.ts
  backend/src/common/enums/ErrorCode.ts
  backend/src/common/mappers/draft.ts
  backend/src/common/models/draft/IDraftClient.ts
  backend/src/common/models/draft/IDraftCommentClient.ts
  backend/src/common/models/draft/IDraftPostClient.ts
  backend/src/data/repositories/draftCommentRepository.ts
  backend/src/data/repositories/draftPostRepository.ts
  backend/src/services/draftService.ts
  frontend/src/common/models/draft/IDraftClient.ts
  frontend/src/containers/Post/styles.module.sass
  frontend/src/scenes/Drafts/components/DraftCard/index.tsx
  frontend/src/scenes/Drafts/components/DraftCard/styles.module.sass
  frontend/src/scenes/Drafts/index.tsx
  frontend/src/scenes/Drafts/reducer/index.ts
  frontend/src/scenes/Drafts/sagas/index.ts
  frontend/src/scenes/Drafts/styles.module.sass
  frontend/src/services/draftService.ts
  frontend/src/services/draftsService.ts
Labels: feature

#187 Welcome message fix
  frontend/src/scenes/Workspace/containers/NoChatMessage/index.tsx
Labels: fix

#201 Fix chat members modal doesn't work properly
  backend/src/data/repositories/chatRepository.ts
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/scenes/Workspace/reducers/index.ts
  frontend/src/scenes/Workspace/routines/index.ts
Labels: fix

#200 Add button disabling
  frontend/src/scenes/Chat/containers/InviteChatForm/index.tsx
  frontend/src/scenes/Chat/containers/InviteChatForm/styles.module.sass
Labels: fix

#199 Add an ability to upload user's profile photo
  backend/.env.example
  backend/package.json
  backend/src/api/routes/awsRoutes.ts
  backend/src/api/routes/index.ts
  backend/src/common/mappers/chat.ts
  backend/src/common/mappers/post.ts
  backend/src/common/mappers/user.ts
  backend/src/common/models/aws/ISignS3.ts
  backend/src/common/models/post/IPost.ts
  backend/src/common/utils/imageHelper.ts
  backend/src/config/awsConfig.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/env.ts
  backend/src/services/awsService.ts
  backend/src/services/workspaceService.ts
  frontend/.env.example
  frontend/package.json
  frontend/src/common/models/aws/ISignResponse.ts
  frontend/src/common/models/cropAvatar/ICropData.ts
  frontend/src/components/CropAvatar/index.tsx
  frontend/src/components/CropAvatar/styles.module.sass
  frontend/src/config/allowedFileTypes.ts
  frontend/src/containers/EditProfileForm/index.tsx
  frontend/src/containers/EditProfileForm/styles.module.sass
  frontend/src/env.ts
  frontend/src/services/awsService.ts
  frontend/src/styles/colors.sass
Labels: feature

#208 Fix region issue
  backend/.env.example
  backend/src/config/awsConfig.ts
  backend/src/env.ts
Labels: fix

#206 Fix "select reaction" container
  frontend/src/components/EmojiPopUp/index.tsx
  frontend/src/components/EmojiPopUp/styles.module.sass
  frontend/src/containers/Post/index.tsx
Labels: fix
