Repository BinaryStudioAcademy/bsa-2020-chatito, pull requests merged in 2020-09, with the labels that each got.

#211 Fix "Delete user isn't working on server"
  backend/src/data/migrations/1598938032275-fixAccountDeletionBehaviour.ts
Labels: fix

#223 Change color border in "Add a direct" field to app's style
  frontend/src/containers/CreateDirectForm/index.tsx
  frontend/src/styles/reset.sass
Labels: fix

#225 Fix uploading photo logic
  backend/src/api/routes/awsRoutes.ts
  backend/src/api/routes/userRoutes.ts
  backend/src/common/utils/imageHelper.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/services/awsService.ts
  backend/src/services/userService.ts
  frontend/.env.example
  frontend/src/common/models/aws/ISignResponse.ts
  frontend/src/common/models/user/IUser.ts
  frontend/src/components/CropAvatar/index.tsx
  frontend/src/containers/EditProfileForm/index.tsx
  frontend/src/containers/ProfileOverview/index.tsx
  frontend/src/containers/ProfilePreview/index.tsx
  frontend/src/env.ts
  frontend/src/reducers/user.ts
  frontend/src/routines/user.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/Chat/containers/ChatHeader/index.tsx
  frontend/src/services/awsService.ts
  frontend/src/services/userService.ts
Labels: fix

#224 In profile overview in the section "About" arrow is always in one-way direction
  frontend/src/containers/ProfileOverview/index.tsx
Labels: fix

#222 Feature/automation init
  automation/package.json
  automation/test/specs/page-objects/add-workspace-page.js
  automation/test/specs/page-objects/login-page.js
  automation/test/specs/seed-data/data.json
  automation/test/specs/tests.js
  automation/wdio.conf.js
Labels: Automation

#241 All "Send" icons should be the same
  frontend/src/containers/ProfileOverview/index.tsx
  frontend/src/containers/ProfilePreview/styles.module.sass
  frontend/src/containers/ProfilePreviewContent/index.tsx
  frontend/src/containers/ProfilePreviewContent/styles.module.sass
  frontend/src/scenes/Drafts/components/DraftCard/index.tsx
Labels: fix

#240 show Display Name instead of Profile in top-right corner
  frontend/src/containers/Header/index.tsx
Labels: fix

#243 Fix updating avatar in post after uploading
  frontend/src/containers/ProfilePreview/index.tsx
Labels: fix

#231 Sound effects. Record own sound
  backend/src/common/mappers/user.ts
  backend/src/common/models/user/IUser.ts
  backend/src/common/models/user/IUserClient.ts
  backend/src/common/models/user/IUserWithWorkspaces.ts
  backend/src/data/entities/User.ts
  backend/src/data/migrations/1598627636284-createdAudio.ts
  backend/src/data/migrations/1599138484503-defaultUserAudio.ts
  backend/src/services/awsService.ts
  backend/src/services/postService.ts
  frontend/package.json
  frontend/src/common/configs/defaults.ts
  frontend/src/common/enums/ModalTypes.ts
  frontend/src/common/helpers/audioHelper.ts
  frontend/src/common/models/user/IUser.ts
  frontend/src/common/sounds/hat_dance.mp3
  frontend/src/components/PlayAudioButton/index.tsx
  frontend/src/components/PlayAudioButton/styles.module.sass
  frontend/src/components/UserPopUp/index.tsx
  frontend/src/containers/AudioRecorder/index.tsx
  frontend/src/containers/AudioRecorder/styles.module.sass
  frontend/src/containers/EditProfileForm/index.tsx
  frontend/src/containers/EditProfileForm/styles.module.sass
  frontend/src/containers/Header/index.tsx
  frontend/src/containers/PreferencesForm/index.tsx
  frontend/src/containers/PreferencesForm/styles.module.sass
  frontend/src/containers/PreferencesModal/index.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/reducers/modal.ts
  frontend/src/reducers/user.ts
  frontend/src/routines/user.ts
  frontend/src/sagas/user.ts
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/scenes/Workspace/reducers/index.ts
  frontend/src/services/awsService.ts
  frontend/src/services/socketService.ts
  frontend/src/styles/reset.sass
Labels: feature

#246 Whale integration
  backend/package.json
  backend/src/common/enums/ChatCommands.ts
  backend/src/common/enums/ClientPostType.ts
  backend/src/common/enums/FetchMethod.ts
  backend/src/common/enums/IntegrationType.ts
  backend/src/common/mappers/post.ts
  backend/src/common/models/apiHelper/IFetchParams.ts
  backend/src/common/models/post/ICreatePost.ts
  backend/src/common/models/post/IPost.ts
  backend/src/data/entities/Post.ts
  backend/src/data/migrations/1599136851961-addIntegrationToPost.ts
  backend/src/data/repositories/postRepository.ts
  backend/src/services/integrationService.ts
  backend/src/services/postService.ts
  frontend/src/common/enums/IntegrationType.ts
  frontend/src/common/enums/MessageType.ts
  frontend/src/common/models/post/IPost.ts
  frontend/src/containers/Post/index.tsx
  frontend/src/scenes/Chat/components/JoinBtn/index.tsx
  frontend/src/scenes/Chat/components/JoinBtn/styles.module.sass
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/services/socketService.ts
  frontend/src/styles/colors.sass
Labels: feature

#242 Show email (disabled) in Profile
  frontend/src/containers/EditProfileForm/index.tsx
Labels: fix

#247 Fix "Members in the chat are displayed incorrectly"
  frontend/src/components/ChatMember/index.tsx
  frontend/src/containers/ChatMembers/index.tsx
Labels: fix

#248 Fix "In Sign Up and Sign In forms the email input is case sensitive"
  backend/src/services/authService.ts
Labels: fix

#245 Incorrectly displayed user photo
  backend/src/api/routes/chatRoutes.ts
  backend/src/common/mappers/comment.ts
  backend/src/common/mappers/post.ts
  backend/src/services/userService.ts
  backend/src/services/workspaceService.ts
Labels: fix

#261 Add possibility to copy link to message
  frontend/src/containers/Post/index.tsx
  frontend/src/containers/Post/styles.module.sass
Labels: feature

#266 schedulia integration
  backend/package.json
  backend/src/api/routes/hooksRoutes.ts
  backend/src/common/enums/IntegrationType.ts
  backend/src/common/mappers/post.ts
  backend/src/config/cors.ts
  backend/src/config/routesWhiteListConfig.ts
  backend/src/data/entities/Post.ts
  backend/src/data/migrations/1599222445046-updateIntegrationEnum.ts
  backend/src/data/migrations/1599237845180-defaultIntegrationType.ts
  backend/src/data/repositories/chatRepository.ts
  backend/src/services/chatService.ts
  backend/src/services/hooksService.ts
  backend/src/services/postService.ts
  backend/src/services/userService.ts
  backend/src/services/workspaceService.ts
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/services/socketService.ts
Labels: fix

#268 Thread names in threads are not displayed
  frontend/src/containers/ThreadsContainer/index.tsx
Labels: bug

#269 Show a number of unread threads next to the Threads option
  frontend/src/containers/Post/index.tsx
  frontend/src/containers/Post/styles.module.sass
  frontend/src/containers/Thread/index.tsx
  frontend/src/containers/Thread/styles.module.sass
  frontend/src/scenes/Workspace/containers/ChatToolbar/index.tsx
  frontend/src/scenes/Workspace/containers/ChatToolbar/styles.module.sass
Labels: fix

#270 minor schedulia integration fix
  backend/src/services/hooksService.ts
Labels: fix

#271 Add an ability to join existing public channel
  backend/src/api/routes/chatRoutes.ts
  backend/src/api/routes/workspaceRoutes.ts
  backend/src/common/mappers/chat.ts
  backend/src/data/repositories/chatRepository.ts
  backend/src/services/chatService.ts
  backend/src/services/workspaceService.ts
  frontend/src/common/enums/FilterType.ts
  frontend/src/common/enums/Routes.ts
  frontend/src/common/enums/SortType.ts
  frontend/src/common/helpers/searchHelper.ts
  frontend/src/common/helpers/sortHelper.ts
  frontend/src/common/models/chat/IBrowserChannel.ts
  frontend/src/common/models/chat/IFetchPublicChannel.ts
  frontend/src/common/models/chat/IJoinOrLeaveChannel.ts
  frontend/src/common/models/sorting/ISortOptions.ts
  frontend/src/common/models/store.ts
  frontend/src/components/CropAvatar/index.tsx
  frontend/src/components/CropAvatar/styles.module.sass
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/ChannelBrowser/components/FilterOption/index.tsx
  frontend/src/scenes/ChannelBrowser/components/FilterOption/styles.module.sass
  frontend/src/scenes/ChannelBrowser/components/SortOption/index.tsx
  frontend/src/scenes/ChannelBrowser/components/SortOption/styles.module.sass
  frontend/src/scenes/ChannelBrowser/containers/ChannelItem/index.tsx
  frontend/src/scenes/ChannelBrowser/containers/ChannelItem/styles.module.sass
  frontend/src/scenes/ChannelBrowser/index.tsx
  frontend/src/scenes/ChannelBrowser/reducer.ts
  frontend/src/scenes/ChannelBrowser/routines.ts
  frontend/src/scenes/ChannelBrowser/sagas.ts
  frontend/src/scenes/ChannelBrowser/styles.module.sass
  frontend/src/scenes/Chat/containers/ChatFooter/index.tsx
  frontend/src/scenes/Chat/containers/ChatFooter/styles.module.sass
  frontend/src/scenes/Chat/index.tsx
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/scenes/Chat/routines/index.ts
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/scenes/Workspace/containers/ChatToolbar/index.tsx
  frontend/src/scenes/Workspace/containers/Workspace/index.tsx
  frontend/src/services/chatService.ts
  frontend/src/services/socketService.ts
  frontend/src/styles/colors.sass
Labels: feature

#272 Divide posts by date
  frontend/src/common/helpers/dateHelper.ts
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/scenes/Chat/containers/ChatBody/styles.module.sass
Labels: feature

#273 Comments in threads are displayed not in the right order
  backend/src/services/workspaceService.ts
Labels: bug

#274 User status limit and UI issue
  backend/src/common/enums/ErrorCode.ts
  backend/src/data/entities/User.ts
  backend/src/data/migrations/1599329315983-updateUsersColumnsMaxLength.ts
  backend/src/services/userService.ts
  frontend/src/containers/EditProfileForm/index.tsx
  frontend/src/containers/ProfileOverview/index.tsx
  frontend/src/containers/ProfileOverview/styles.module.sass
  frontend/src/containers/ProfilePreviewContent/index.tsx
  frontend/src/containers/ProfilePreviewContent/styles.module.sass
  frontend/src/sagas/user.ts
Labels: bug

#275 fixedIn profile overview add texts to buttons
  frontend/src/containers/ProfileOverview/index.tsx
  frontend/src/containers/ProfileOverview/styles.module.sass
Labels: fix

#276 Remove blue color from 'Create an account', 'Forgot password' and in "About" in Profile Overview
  frontend/src/containers/ProfileOverview/styles.module.sass
Labels: bug

#277 Add margin over input field
  frontend/src/containers/CreateRepositoryChatModal/styles.module.sass
Labels: fix

#279 Profile overview and Thread doesn't disappear when workspaces change
  frontend/src/scenes/Workspace/containers/WorkspaceToolbar/components/WorkspaceItem/index.tsx
  frontend/src/scenes/Workspace/reducers/index.ts
Labels: bug

#283 Thread notifications of one workspace are displayed in all other workspaces
  backend/src/api/routes/userRoutes.ts
  backend/src/api/routes/workspaceRoutes.ts
  backend/src/common/models/user/IUserUnreadPosts.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/services/userService.ts
  frontend/src/common/models/post/IFetchWorkspaceUnreadComments.ts
  frontend/src/common/models/post/IFetchWorkspaceUnreadPosts.ts
  frontend/src/scenes/Workspace/containers/Workspace/index.tsx
  frontend/src/scenes/Workspace/reducers/index.ts
  frontend/src/scenes/Workspace/sagas/index.ts
  frontend/src/services/userService.ts
Labels: bug

#284 Change the color of green buttons
  frontend/src/containers/AudioRecorder/styles.module.sass
  frontend/src/containers/EditProfileForm/index.tsx
  frontend/src/containers/EditProfileForm/styles.module.sass
  frontend/src/containers/PreferencesForm/index.tsx
  frontend/src/containers/PreferencesForm/styles.module.sass
Labels: fix

#288 In direct messages, user's profile overview doesn't open
  frontend/src/scenes/Chat/containers/ChatHeader/index.tsx
Labels: feature

#289 Fix Profile Overview toolbar
  backend/src/data/repositories/userRepository.ts
  frontend/src/containers/ProfileOverview/index.tsx
  frontend/src/containers/ProfileOverview/styles.module.sass
Labels: bug

#292 In custom reminder creation make the date in English + fix UI
  backend/src/services/postService.ts
  frontend/package.json
  frontend/src/containers/CustomReminderModal/index.tsx
  frontend/src/containers/CustomReminderModal/styles.module.sass
  frontend/src/containers/Post/index.tsx
  frontend/src/scenes/Drafts/components/DraftCard/index.tsx
  frontend/src/styles/colors.sass
  frontend/src/styles/index.sass
Labels: fix

#306 Channel does not appear right away in invited user's list of channels
  backend/src/api/routes/chatRoutes.ts
  backend/src/common/enums/ClientSockets.ts
  backend/src/common/enums/ServerSockets.ts
  backend/src/data/repositories/chatRepository.ts
  backend/src/services/chatService.ts
  backend/src/services/hooksService.ts
  backend/src/services/socketService.ts
  backend/src/socket/chatHandlers.ts
  frontend/src/common/enums/ClientSockets.ts
  frontend/src/common/enums/ServerSockets.ts
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/scenes/Workspace/reducers/index.ts
  frontend/src/scenes/Workspace/routines/index.ts
  frontend/src/services/socketService.ts
Labels: fix

#307 Unable to remove photo from the profile/upload new photo
  backend/src/services/userService.ts
  frontend/src/containers/EditProfileForm/index.tsx
Labels: fix

#310 Hotfix of using 'react-datetime-picker' module
  frontend/src/containers/CustomReminderModal/index.tsx
  frontend/src/react-app-env.d.ts
Labels: fix

#313 Remove unused props param
  frontend/src/containers/ChatMembers/index.tsx
Labels: fix

#309 Fix "Add user popup overlays the channel members popup"
  frontend/src/containers/ChatMembers/index.tsx
  frontend/src/scenes/Chat/containers/InviteChatModal/index.tsx
Labels: fix

#316 Routing bug in direct chat
  frontend/src/scenes/Chat/index.tsx
Labels: fix

#312 Add an ability to mute a chat
  backend/src/api/routes/chatRoutes.ts
  backend/src/common/enums/ClientSockets.ts
  backend/src/common/mappers/chat.ts
  backend/src/data/entities/Chat.ts
  backend/src/data/entities/User.ts
  backend/src/data/migrations/1599467314311-ChatMute.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/services/chatService.ts
  backend/src/services/workspaceService.ts
  frontend/src/common/enums/ClientSockets.ts
  frontend/src/common/models/chat/IChat.ts
  frontend/src/scenes/Chat/containers/ChatHeader/index.tsx
  frontend/src/scenes/Chat/containers/ChatHeader/styles.module.sass
  frontend/src/scenes/Chat/reducers/index.ts
  frontend/src/scenes/Chat/routines/index.ts
  frontend/src/scenes/Chat/sagas/index.ts
  frontend/src/scenes/Workspace/containers/ChatToolbar/index.tsx
  frontend/src/scenes/Workspace/containers/ChatToolbar/styles.module.sass
  frontend/src/scenes/Workspace/reducers/index.ts
  frontend/src/services/chatService.ts
  frontend/src/services/socketService.ts
Labels: feature

#322 move info icon from chat header
  frontend/src/scenes/Chat/containers/ChatHeader/index.tsx
Labels: fix

#324 After closing "Add members" popup, the Chat members popup appears
  frontend/src/scenes/Chat/containers/InviteChatModal/index.tsx
  frontend/src/scenes/Drafts/components/DraftCard/index.tsx
Labels: fix

#328 Login issue: another user can write in a chat, where he hasn't been added
  frontend/src/containers/Routing/index.tsx
  frontend/src/services/authService.ts
Labels: fix

#329 Hide functionality from public channel
  frontend/src/common/models/chat/IJoinChannel.ts
  frontend/src/containers/ChatMembers/index.tsx
  frontend/src/containers/Post/index.tsx
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
  frontend/src/scenes/Chat/containers/ChatFooter/index.tsx
  frontend/src/scenes/Chat/containers/ChatHeader/index.tsx
  frontend/src/scenes/Chat/index.tsx
Labels: fix

#330 removed info from direcs
  frontend/src/scenes/Chat/containers/ChatHeader/index.tsx
Labels: fix

#332 align changed
  frontend/src/scenes/Drafts/components/DraftCard/styles.module.sass
Labels: fix

#335 When user sends a message, he has to manually scroll down to see it
  frontend/src/common/hooks/usePrevious.ts
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
Labels: fix

#337 Save button does not work in Preferences
  frontend/src/containers/PreferencesForm/index.tsx
Labels: fix

#343 When Join to invited workspace (already logged in) avatar is not loaded
  backend/src/api/routes/userRoutes.ts
  backend/src/services/userService.ts
Labels: fix

#346 Add limit on direct messages members
  frontend/src/containers/CreateDirectForm/index.tsx
  frontend/src/containers/CreateDirectForm/styles.module.sass
  frontend/src/styles/reset.sass
Labels: fix

#349 Fix reset and preference modal styles
  frontend/src/containers/CreateDirectForm/styles.module.sass
  frontend/src/styles/reset.sass
Labels: fix

#359 When the user signed in using facebook, his avatar "crushed"
  backend/src/common/utils/imageHelper.ts
Labels: fix

#362 Fix rendering react button and more options
  backend/src/data/repositories/postRepository.ts
  frontend/src/common/models/threads/IFetchedThreads.ts
  frontend/src/containers/Post/index.tsx
  frontend/src/containers/ThreadsContainer/index.tsx
  frontend/src/scenes/Chat/containers/ChatBody/index.tsx
Labels: fix

#365 Fix fetching public chat
  frontend/src/scenes/Chat/index.tsx
Labels: fix

#366 Fix bug with buttons on the Channel Browser page
  frontend/src/scenes/ChannelBrowser/containers/ChannelItem/index.tsx
  frontend/src/scenes/ChannelBrowser/containers/ChannelItem/styles.module.sass
  frontend/src/scenes/ChannelBrowser/reducer.ts
Labels: fix

#375 Login inputs UI fix
  frontend/src/components/InputField/InputField.tsx
  frontend/src/components/InputField/styles.module.sass
  frontend/src/scenes/Auth/components/SignIn/index.tsx
  frontend/src/scenes/Auth/components/SignIn/styles.module.sass
  frontend/src/scenes/Auth/components/SignUp/index.tsx
Labels: fix

#376 Fix a bug with channel description
  backend/src/data/repositories/chatRepository.ts
Labels: fix

#380 Fix auth and Join Whale btn styles
  frontend/src/components/InputField/InputField.tsx
  frontend/src/components/InputField/styles.module.sass
  frontend/src/scenes/Chat/components/JoinBtn/styles.module.sass
Labels: fix

#381 Show displayName instead of fullName in chat
  frontend/src/containers/Post/index.tsx
Labels: fix

#379 Fix creating chats with the same name
  backend/src/common/enums/ErrorCode.ts
  backend/src/data/entities/Chat.ts
  backend/src/data/migrations/1599815618664-ChatNameConstraint.ts
  backend/src/services/chatService.ts
Labels: fix

#386 Fix the possibility of an empty user name
  frontend/src/containers/EditProfileForm/index.tsx
  frontend/src/containers/Post/index.tsx
Labels: fix

#388 Fix saving direct message in db
  backend/src/services/chatService.ts
Labels: fix

#389 Fix empty displayName
  frontend/src/containers/EditProfileForm/index.tsx
  frontend/src/containers/Post/index.tsx
Labels: fix
